# Generated by Django 5.0.7 on 2024-10-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('Manager', 'Manager'), ('product owner', 'Product owner'), ('tester', 'tester')], max_length=50),
        ),
    ]
